2025-06-11 22:06:53,090:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:06:53,091:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:06:53,091:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:06:53,091:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:06:57,159:INFO:PyCaret ClassificationExperiment
2025-06-11 22:06:57,159:INFO:Logging name: credit_approval
2025-06-11 22:06:57,161:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-06-11 22:06:57,161:INFO:version 3.2.0
2025-06-11 22:06:57,161:INFO:Initializing setup()
2025-06-11 22:06:57,161:INFO:self.USI: 80e6
2025-06-11 22:06:57,161:INFO:self._variable_keys: {'html_param', 'logging_param', 'seed', 'pipeline', 'X_test', 'fold_groups_param', 'y', 'y_train', '_available_plots', 'exp_name_log', 'gpu_n_jobs_param', 'exp_id', 'data', 'X', 'y_test', 'gpu_param', 'fold_generator', 'target_param', 'USI', 'n_jobs_param', 'is_multiclass', 'idx', 'fix_imbalance', 'memory', '_ml_usecase', 'X_train', 'fold_shuffle_param', 'log_plots_param'}
2025-06-11 22:06:57,161:INFO:Checking environment
2025-06-11 22:06:57,161:INFO:python_version: 3.11.8
2025-06-11 22:06:57,161:INFO:python_build: ('tags/v3.11.8:db85d51', 'Feb  6 2024 22:03:32')
2025-06-11 22:06:57,161:INFO:machine: AMD64
2025-06-11 22:06:57,171:INFO:platform: Windows-10-10.0.26100-SP0
2025-06-11 22:06:57,176:INFO:Memory: svmem(total=16907886592, available=4433121280, percent=73.8, used=12474765312, free=4433121280)
2025-06-11 22:06:57,176:INFO:Physical Core: 4
2025-06-11 22:06:57,176:INFO:Logical Core: 8
2025-06-11 22:06:57,176:INFO:Checking libraries
2025-06-11 22:06:57,176:INFO:System:
2025-06-11 22:06:57,176:INFO:    python: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
2025-06-11 22:06:57,176:INFO:executable: C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe
2025-06-11 22:06:57,176:INFO:   machine: Windows-10-10.0.26100-SP0
2025-06-11 22:06:57,176:INFO:PyCaret required dependencies:
2025-06-11 22:06:57,740:INFO:                 pip: 24.0
2025-06-11 22:06:57,740:INFO:          setuptools: 65.5.0
2025-06-11 22:06:57,740:INFO:             pycaret: 3.2.0
2025-06-11 22:06:57,740:INFO:             IPython: 9.2.0
2025-06-11 22:06:57,740:INFO:          ipywidgets: 8.1.7
2025-06-11 22:06:57,740:INFO:                tqdm: 4.67.1
2025-06-11 22:06:57,740:INFO:               numpy: 1.25.2
2025-06-11 22:06:57,740:INFO:              pandas: 1.5.3
2025-06-11 22:06:57,740:INFO:              jinja2: 3.1.6
2025-06-11 22:06:57,740:INFO:               scipy: 1.10.1
2025-06-11 22:06:57,740:INFO:              joblib: 1.3.2
2025-06-11 22:06:57,740:INFO:             sklearn: 1.2.2
2025-06-11 22:06:57,740:INFO:                pyod: 2.0.5
2025-06-11 22:06:57,740:INFO:            imblearn: 0.12.4
2025-06-11 22:06:57,740:INFO:   category_encoders: 2.7.0
2025-06-11 22:06:57,740:INFO:            lightgbm: 4.6.0
2025-06-11 22:06:57,740:INFO:               numba: 0.58.1
2025-06-11 22:06:57,740:INFO:            requests: 2.32.3
2025-06-11 22:06:57,740:INFO:          matplotlib: 3.6.0
2025-06-11 22:06:57,740:INFO:          scikitplot: 0.3.7
2025-06-11 22:06:57,740:INFO:         yellowbrick: 1.5
2025-06-11 22:06:57,740:INFO:              plotly: 5.24.1
2025-06-11 22:06:57,740:INFO:    plotly-resampler: Not installed
2025-06-11 22:06:57,740:INFO:             kaleido: 0.2.1
2025-06-11 22:06:57,740:INFO:           schemdraw: 0.15
2025-06-11 22:06:57,740:INFO:         statsmodels: 0.14.4
2025-06-11 22:06:57,740:INFO:              sktime: 0.21.1
2025-06-11 22:06:57,740:INFO:               tbats: 1.1.3
2025-06-11 22:06:57,740:INFO:            pmdarima: 2.0.4
2025-06-11 22:06:57,741:INFO:              psutil: 7.0.0
2025-06-11 22:06:57,741:INFO:          markupsafe: 2.1.5
2025-06-11 22:06:57,741:INFO:             pickle5: Not installed
2025-06-11 22:06:57,741:INFO:         cloudpickle: 2.2.1
2025-06-11 22:06:57,741:INFO:         deprecation: 2.1.0
2025-06-11 22:06:57,741:INFO:              xxhash: 3.5.0
2025-06-11 22:06:57,741:INFO:           wurlitzer: Not installed
2025-06-11 22:06:57,741:INFO:PyCaret optional dependencies:
2025-06-11 22:06:59,218:INFO:                shap: 0.44.1
2025-06-11 22:06:59,218:INFO:           interpret: 0.6.10
2025-06-11 22:06:59,219:INFO:                umap: 0.5.7
2025-06-11 22:06:59,219:INFO:     ydata_profiling: 4.6.0
2025-06-11 22:06:59,219:INFO:  explainerdashboard: 0.4.8
2025-06-11 22:06:59,219:INFO:             autoviz: Not installed
2025-06-11 22:06:59,219:INFO:           fairlearn: 0.7.0
2025-06-11 22:06:59,219:INFO:          deepchecks: Not installed
2025-06-11 22:06:59,219:INFO:             xgboost: Not installed
2025-06-11 22:06:59,219:INFO:            catboost: 1.2.8
2025-06-11 22:06:59,219:INFO:              kmodes: 0.12.2
2025-06-11 22:06:59,219:INFO:             mlxtend: 0.23.1
2025-06-11 22:06:59,219:INFO:       statsforecast: 1.5.0
2025-06-11 22:06:59,219:INFO:        tune_sklearn: Not installed
2025-06-11 22:06:59,219:INFO:                 ray: Not installed
2025-06-11 22:06:59,219:INFO:            hyperopt: 0.2.7
2025-06-11 22:06:59,219:INFO:              optuna: 4.3.0
2025-06-11 22:06:59,219:INFO:               skopt: 0.10.2
2025-06-11 22:06:59,219:INFO:              mlflow: 2.22.0
2025-06-11 22:06:59,219:INFO:              gradio: 3.50.2
2025-06-11 22:06:59,219:INFO:             fastapi: 0.115.12
2025-06-11 22:06:59,219:INFO:             uvicorn: 0.34.2
2025-06-11 22:06:59,219:INFO:              m2cgen: 0.10.0
2025-06-11 22:06:59,220:INFO:           evidently: 0.2.8
2025-06-11 22:06:59,220:INFO:               fugue: 0.8.6
2025-06-11 22:06:59,220:INFO:           streamlit: 1.45.1
2025-06-11 22:06:59,220:INFO:             prophet: Not installed
2025-06-11 22:06:59,220:INFO:None
2025-06-11 22:06:59,220:INFO:Set up data.
2025-06-11 22:08:17,465:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:08:17,465:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:08:17,465:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:08:17,465:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:08:21,207:INFO:PyCaret ClassificationExperiment
2025-06-11 22:08:21,207:INFO:Logging name: credit_approval
2025-06-11 22:08:21,207:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-06-11 22:08:21,207:INFO:version 3.2.0
2025-06-11 22:08:21,207:INFO:Initializing setup()
2025-06-11 22:08:21,207:INFO:self.USI: f3ba
2025-06-11 22:08:21,207:INFO:self._variable_keys: {'gpu_n_jobs_param', 'y', 'data', 'fix_imbalance', 'pipeline', 'exp_name_log', 'fold_groups_param', 'idx', 'target_param', '_ml_usecase', 'is_multiclass', 'X_test', 'fold_shuffle_param', 'html_param', 'USI', 'exp_id', 'y_test', 'fold_generator', 'seed', 'n_jobs_param', 'logging_param', 'y_train', 'X_train', 'X', 'memory', 'gpu_param', 'log_plots_param', '_available_plots'}
2025-06-11 22:08:21,207:INFO:Checking environment
2025-06-11 22:08:21,207:INFO:python_version: 3.11.8
2025-06-11 22:08:21,207:INFO:python_build: ('tags/v3.11.8:db85d51', 'Feb  6 2024 22:03:32')
2025-06-11 22:08:21,207:INFO:machine: AMD64
2025-06-11 22:08:21,218:INFO:platform: Windows-10-10.0.26100-SP0
2025-06-11 22:08:21,223:INFO:Memory: svmem(total=16907886592, available=4425142272, percent=73.8, used=12482744320, free=4425142272)
2025-06-11 22:08:21,223:INFO:Physical Core: 4
2025-06-11 22:08:21,223:INFO:Logical Core: 8
2025-06-11 22:08:21,223:INFO:Checking libraries
2025-06-11 22:08:21,223:INFO:System:
2025-06-11 22:08:21,223:INFO:    python: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
2025-06-11 22:08:21,223:INFO:executable: C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe
2025-06-11 22:08:21,224:INFO:   machine: Windows-10-10.0.26100-SP0
2025-06-11 22:08:21,224:INFO:PyCaret required dependencies:
2025-06-11 22:08:21,777:INFO:                 pip: 24.0
2025-06-11 22:08:21,777:INFO:          setuptools: 65.5.0
2025-06-11 22:08:21,777:INFO:             pycaret: 3.2.0
2025-06-11 22:08:21,777:INFO:             IPython: 9.2.0
2025-06-11 22:08:21,777:INFO:          ipywidgets: 8.1.7
2025-06-11 22:08:21,777:INFO:                tqdm: 4.67.1
2025-06-11 22:08:21,777:INFO:               numpy: 1.25.2
2025-06-11 22:08:21,777:INFO:              pandas: 1.5.3
2025-06-11 22:08:21,777:INFO:              jinja2: 3.1.6
2025-06-11 22:08:21,777:INFO:               scipy: 1.10.1
2025-06-11 22:08:21,777:INFO:              joblib: 1.3.2
2025-06-11 22:08:21,777:INFO:             sklearn: 1.2.2
2025-06-11 22:08:21,777:INFO:                pyod: 2.0.5
2025-06-11 22:08:21,777:INFO:            imblearn: 0.12.4
2025-06-11 22:08:21,777:INFO:   category_encoders: 2.7.0
2025-06-11 22:08:21,777:INFO:            lightgbm: 4.6.0
2025-06-11 22:08:21,777:INFO:               numba: 0.58.1
2025-06-11 22:08:21,777:INFO:            requests: 2.32.3
2025-06-11 22:08:21,777:INFO:          matplotlib: 3.6.0
2025-06-11 22:08:21,777:INFO:          scikitplot: 0.3.7
2025-06-11 22:08:21,777:INFO:         yellowbrick: 1.5
2025-06-11 22:08:21,777:INFO:              plotly: 5.24.1
2025-06-11 22:08:21,777:INFO:    plotly-resampler: Not installed
2025-06-11 22:08:21,777:INFO:             kaleido: 0.2.1
2025-06-11 22:08:21,777:INFO:           schemdraw: 0.15
2025-06-11 22:08:21,777:INFO:         statsmodels: 0.14.4
2025-06-11 22:08:21,777:INFO:              sktime: 0.21.1
2025-06-11 22:08:21,777:INFO:               tbats: 1.1.3
2025-06-11 22:08:21,778:INFO:            pmdarima: 2.0.4
2025-06-11 22:08:21,778:INFO:              psutil: 7.0.0
2025-06-11 22:08:21,778:INFO:          markupsafe: 2.1.5
2025-06-11 22:08:21,778:INFO:             pickle5: Not installed
2025-06-11 22:08:21,778:INFO:         cloudpickle: 2.2.1
2025-06-11 22:08:21,778:INFO:         deprecation: 2.1.0
2025-06-11 22:08:21,778:INFO:              xxhash: 3.5.0
2025-06-11 22:08:21,778:INFO:           wurlitzer: Not installed
2025-06-11 22:08:21,778:INFO:PyCaret optional dependencies:
2025-06-11 22:08:22,866:INFO:                shap: 0.44.1
2025-06-11 22:08:22,866:INFO:           interpret: 0.6.10
2025-06-11 22:08:22,866:INFO:                umap: 0.5.7
2025-06-11 22:08:22,866:INFO:     ydata_profiling: 4.6.0
2025-06-11 22:08:22,866:INFO:  explainerdashboard: 0.4.8
2025-06-11 22:08:22,866:INFO:             autoviz: Not installed
2025-06-11 22:08:22,866:INFO:           fairlearn: 0.7.0
2025-06-11 22:08:22,866:INFO:          deepchecks: Not installed
2025-06-11 22:08:22,866:INFO:             xgboost: Not installed
2025-06-11 22:08:22,866:INFO:            catboost: 1.2.8
2025-06-11 22:08:22,866:INFO:              kmodes: 0.12.2
2025-06-11 22:08:22,866:INFO:             mlxtend: 0.23.1
2025-06-11 22:08:22,866:INFO:       statsforecast: 1.5.0
2025-06-11 22:08:22,867:INFO:        tune_sklearn: Not installed
2025-06-11 22:08:22,867:INFO:                 ray: Not installed
2025-06-11 22:08:22,867:INFO:            hyperopt: 0.2.7
2025-06-11 22:08:22,867:INFO:              optuna: 4.3.0
2025-06-11 22:08:22,867:INFO:               skopt: 0.10.2
2025-06-11 22:08:22,867:INFO:              mlflow: 2.22.0
2025-06-11 22:08:22,867:INFO:              gradio: 3.50.2
2025-06-11 22:08:22,867:INFO:             fastapi: 0.115.12
2025-06-11 22:08:22,867:INFO:             uvicorn: 0.34.2
2025-06-11 22:08:22,867:INFO:              m2cgen: 0.10.0
2025-06-11 22:08:22,867:INFO:           evidently: 0.2.8
2025-06-11 22:08:22,867:INFO:               fugue: 0.8.6
2025-06-11 22:08:22,867:INFO:           streamlit: 1.45.1
2025-06-11 22:08:22,867:INFO:             prophet: Not installed
2025-06-11 22:08:22,867:INFO:None
2025-06-11 22:08:22,867:INFO:Set up data.
2025-06-11 22:08:22,872:INFO:Set up folding strategy.
2025-06-11 22:08:22,872:INFO:Set up train/test split.
2025-06-11 22:08:22,875:INFO:Set up index.
2025-06-11 22:08:22,875:INFO:Assigning column types.
2025-06-11 22:08:22,878:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2025-06-11 22:08:22,911:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-06-11 22:08:22,914:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-06-11 22:08:22,941:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:22,941:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,001:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-06-11 22:08:23,002:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-06-11 22:08:23,023:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,023:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,024:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2025-06-11 22:08:23,059:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-06-11 22:08:23,082:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,083:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,121:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-06-11 22:08:23,144:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,145:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,146:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2025-06-11 22:08:23,205:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,206:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,263:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,263:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,264:INFO:Preparing preprocessing pipeline...
2025-06-11 22:08:23,265:INFO:Set up simple imputation.
2025-06-11 22:08:23,267:INFO:Set up encoding of categorical features.
2025-06-11 22:08:23,304:INFO:Finished creating preprocessing pipeline.
2025-06-11 22:08:23,308:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\User\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'monthly_income_usd',
                                             'app_usage_score',
                                             'digital_profile_strength',
                                             'num_contacts_uploaded',
                                             'political_event_last_month'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_e...
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('onehot_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['residence_risk_zone'],
                                    transformer=OneHotEncoder(cols=['residence_risk_zone'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0)))],
         verbose=False)
2025-06-11 22:08:23,308:INFO:Creating final display dataframe.
2025-06-11 22:08:23,420:INFO:Setup _display_container:                     Description            Value
0                    Session id              606
1                        Target         approved
2                   Target type           Binary
3           Original data shape        (1000, 8)
4        Transformed data shape       (1000, 10)
5   Transformed train set shape        (700, 10)
6    Transformed test set shape        (300, 10)
7              Numeric features                6
8          Categorical features                1
9                    Preprocess             True
10              Imputation type           simple
11           Numeric imputation             mean
12       Categorical imputation             mode
13     Maximum one-hot encoding               25
14              Encoding method             None
15               Fold Generator  StratifiedKFold
16                  Fold Number               10
17                     CPU Jobs               -1
18                      Use GPU            False
19               Log Experiment     MlflowLogger
20              Experiment Name  credit_approval
21                          USI             f3ba
2025-06-11 22:08:23,484:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,484:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,550:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-06-11 22:08:23,551:INFO:Soft dependency imported: catboost: 1.2.8
2025-06-11 22:08:23,551:INFO:Logging experiment in loggers
2025-06-11 22:08:23,917:INFO:SubProcess save_model() called ==================================
2025-06-11 22:08:23,925:INFO:Initializing save_model()
2025-06-11 22:08:23,925:INFO:save_model(model=Pipeline(memory=FastMemory(location=C:\Users\User\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'monthly_income_usd',
                                             'app_usage_score',
                                             'digital_profile_strength',
                                             'num_contacts_uploaded',
                                             'political_event_last_month'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_e...
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('onehot_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['residence_risk_zone'],
                                    transformer=OneHotEncoder(cols=['residence_risk_zone'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0)))],
         verbose=False), model_name=C:\Users\User\AppData\Local\Temp\tmprg0ap0zo\Transformation Pipeline, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\User\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'monthly_income_usd',
                                             'app_usage_score',
                                             'digital_profile_strength',
                                             'num_contacts_uploaded',
                                             'political_event_last_month'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_e...
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('onehot_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['residence_risk_zone'],
                                    transformer=OneHotEncoder(cols=['residence_risk_zone'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0)))],
         verbose=False), verbose=False, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2025-06-11 22:08:23,925:INFO:Adding model into prep_pipe
2025-06-11 22:08:23,925:WARNING:Only Model saved as it was a pipeline.
2025-06-11 22:08:23,929:INFO:C:\Users\User\AppData\Local\Temp\tmprg0ap0zo\Transformation Pipeline.pkl saved in current working directory
2025-06-11 22:08:23,934:INFO:Pipeline(memory=FastMemory(location=C:\Users\User\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'monthly_income_usd',
                                             'app_usage_score',
                                             'digital_profile_strength',
                                             'num_contacts_uploaded',
                                             'political_event_last_month'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_e...
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('onehot_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['residence_risk_zone'],
                                    transformer=OneHotEncoder(cols=['residence_risk_zone'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0)))],
         verbose=False)
2025-06-11 22:08:23,934:INFO:save_model() successfully completed......................................
2025-06-11 22:08:24,028:INFO:SubProcess save_model() end ==================================
2025-06-11 22:08:24,155:INFO:setup() successfully completed in 2.35s...............
2025-06-11 22:08:24,156:INFO:Initializing compare_models()
2025-06-11 22:08:24,156:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, include=None, exclude=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2025-06-11 22:08:24,156:INFO:Checking exceptions
2025-06-11 22:08:24,158:INFO:Preparing display monitor
2025-06-11 22:08:24,162:INFO:Initializing Logistic Regression
2025-06-11 22:08:24,162:INFO:Total runtime is 0.0 minutes
2025-06-11 22:08:24,162:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:24,163:INFO:Initializing create_model()
2025-06-11 22:08:24,163:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:24,163:INFO:Checking exceptions
2025-06-11 22:08:24,163:INFO:Importing libraries
2025-06-11 22:08:24,163:INFO:Copying training dataset
2025-06-11 22:08:24,165:INFO:Defining folds
2025-06-11 22:08:24,165:INFO:Declaring metric variables
2025-06-11 22:08:24,165:INFO:Importing untrained model
2025-06-11 22:08:24,167:INFO:Logistic Regression Imported successfully
2025-06-11 22:08:24,167:INFO:Starting cross validation
2025-06-11 22:08:24,168:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:38,503:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-06-11 22:08:38,653:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-06-11 22:08:38,815:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-06-11 22:08:38,964:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-06-11 22:08:39,056:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-06-11 22:08:39,169:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-06-11 22:08:39,205:INFO:Calculating mean and std
2025-06-11 22:08:39,207:INFO:Creating metrics dataframe
2025-06-11 22:08:39,212:INFO:Uploading results into container
2025-06-11 22:08:39,214:INFO:Uploading model into container now
2025-06-11 22:08:39,214:INFO:_master_model_container: 1
2025-06-11 22:08:39,214:INFO:_display_container: 2
2025-06-11 22:08:39,215:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=606, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-06-11 22:08:39,216:INFO:create_model() successfully completed......................................
2025-06-11 22:08:39,329:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:39,329:INFO:Creating metrics dataframe
2025-06-11 22:08:39,333:INFO:Initializing K Neighbors Classifier
2025-06-11 22:08:39,333:INFO:Total runtime is 0.25285375118255615 minutes
2025-06-11 22:08:39,334:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:39,334:INFO:Initializing create_model()
2025-06-11 22:08:39,334:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:39,334:INFO:Checking exceptions
2025-06-11 22:08:39,334:INFO:Importing libraries
2025-06-11 22:08:39,334:INFO:Copying training dataset
2025-06-11 22:08:39,337:INFO:Defining folds
2025-06-11 22:08:39,337:INFO:Declaring metric variables
2025-06-11 22:08:39,339:INFO:Importing untrained model
2025-06-11 22:08:39,339:INFO:K Neighbors Classifier Imported successfully
2025-06-11 22:08:39,339:INFO:Starting cross validation
2025-06-11 22:08:39,339:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:39,673:INFO:Calculating mean and std
2025-06-11 22:08:39,674:INFO:Creating metrics dataframe
2025-06-11 22:08:39,680:INFO:Uploading results into container
2025-06-11 22:08:39,681:INFO:Uploading model into container now
2025-06-11 22:08:39,681:INFO:_master_model_container: 2
2025-06-11 22:08:39,682:INFO:_display_container: 2
2025-06-11 22:08:39,682:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2025-06-11 22:08:39,682:INFO:create_model() successfully completed......................................
2025-06-11 22:08:39,784:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:39,784:INFO:Creating metrics dataframe
2025-06-11 22:08:39,789:INFO:Initializing Naive Bayes
2025-06-11 22:08:39,789:INFO:Total runtime is 0.26045474608739216 minutes
2025-06-11 22:08:39,790:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:39,790:INFO:Initializing create_model()
2025-06-11 22:08:39,790:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:39,790:INFO:Checking exceptions
2025-06-11 22:08:39,790:INFO:Importing libraries
2025-06-11 22:08:39,790:INFO:Copying training dataset
2025-06-11 22:08:39,794:INFO:Defining folds
2025-06-11 22:08:39,794:INFO:Declaring metric variables
2025-06-11 22:08:39,794:INFO:Importing untrained model
2025-06-11 22:08:39,794:INFO:Naive Bayes Imported successfully
2025-06-11 22:08:39,794:INFO:Starting cross validation
2025-06-11 22:08:39,795:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:39,993:INFO:Calculating mean and std
2025-06-11 22:08:39,994:INFO:Creating metrics dataframe
2025-06-11 22:08:39,997:INFO:Uploading results into container
2025-06-11 22:08:39,998:INFO:Uploading model into container now
2025-06-11 22:08:39,998:INFO:_master_model_container: 3
2025-06-11 22:08:39,998:INFO:_display_container: 2
2025-06-11 22:08:39,998:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2025-06-11 22:08:39,998:INFO:create_model() successfully completed......................................
2025-06-11 22:08:40,100:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:40,100:INFO:Creating metrics dataframe
2025-06-11 22:08:40,104:INFO:Initializing Decision Tree Classifier
2025-06-11 22:08:40,104:INFO:Total runtime is 0.2657028595606486 minutes
2025-06-11 22:08:40,105:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:40,105:INFO:Initializing create_model()
2025-06-11 22:08:40,105:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:40,105:INFO:Checking exceptions
2025-06-11 22:08:40,105:INFO:Importing libraries
2025-06-11 22:08:40,106:INFO:Copying training dataset
2025-06-11 22:08:40,109:INFO:Defining folds
2025-06-11 22:08:40,109:INFO:Declaring metric variables
2025-06-11 22:08:40,109:INFO:Importing untrained model
2025-06-11 22:08:40,109:INFO:Decision Tree Classifier Imported successfully
2025-06-11 22:08:40,109:INFO:Starting cross validation
2025-06-11 22:08:40,110:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:40,307:INFO:Calculating mean and std
2025-06-11 22:08:40,308:INFO:Creating metrics dataframe
2025-06-11 22:08:40,312:INFO:Uploading results into container
2025-06-11 22:08:40,312:INFO:Uploading model into container now
2025-06-11 22:08:40,313:INFO:_master_model_container: 4
2025-06-11 22:08:40,313:INFO:_display_container: 2
2025-06-11 22:08:40,313:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=606, splitter='best')
2025-06-11 22:08:40,313:INFO:create_model() successfully completed......................................
2025-06-11 22:08:40,416:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:40,416:INFO:Creating metrics dataframe
2025-06-11 22:08:40,422:INFO:Initializing SVM - Linear Kernel
2025-06-11 22:08:40,422:INFO:Total runtime is 0.2709971030553182 minutes
2025-06-11 22:08:40,422:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:40,422:INFO:Initializing create_model()
2025-06-11 22:08:40,422:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:40,422:INFO:Checking exceptions
2025-06-11 22:08:40,422:INFO:Importing libraries
2025-06-11 22:08:40,422:INFO:Copying training dataset
2025-06-11 22:08:40,426:INFO:Defining folds
2025-06-11 22:08:40,426:INFO:Declaring metric variables
2025-06-11 22:08:40,426:INFO:Importing untrained model
2025-06-11 22:08:40,427:INFO:SVM - Linear Kernel Imported successfully
2025-06-11 22:08:40,427:INFO:Starting cross validation
2025-06-11 22:08:40,427:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:40,543:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,545:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,548:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,551:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,552:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,554:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,577:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,637:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,637:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-06-11 22:08:40,648:INFO:Calculating mean and std
2025-06-11 22:08:40,649:INFO:Creating metrics dataframe
2025-06-11 22:08:40,652:INFO:Uploading results into container
2025-06-11 22:08:40,653:INFO:Uploading model into container now
2025-06-11 22:08:40,653:INFO:_master_model_container: 5
2025-06-11 22:08:40,654:INFO:_display_container: 2
2025-06-11 22:08:40,654:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=606, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2025-06-11 22:08:40,654:INFO:create_model() successfully completed......................................
2025-06-11 22:08:40,760:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:40,760:INFO:Creating metrics dataframe
2025-06-11 22:08:40,765:INFO:Initializing Ridge Classifier
2025-06-11 22:08:40,765:INFO:Total runtime is 0.27672544320424397 minutes
2025-06-11 22:08:40,765:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:40,765:INFO:Initializing create_model()
2025-06-11 22:08:40,765:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:40,765:INFO:Checking exceptions
2025-06-11 22:08:40,765:INFO:Importing libraries
2025-06-11 22:08:40,765:INFO:Copying training dataset
2025-06-11 22:08:40,770:INFO:Defining folds
2025-06-11 22:08:40,770:INFO:Declaring metric variables
2025-06-11 22:08:40,770:INFO:Importing untrained model
2025-06-11 22:08:40,770:INFO:Ridge Classifier Imported successfully
2025-06-11 22:08:40,771:INFO:Starting cross validation
2025-06-11 22:08:40,772:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:40,881:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,883:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,887:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,888:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,890:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,892:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,901:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,913:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,977:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,978:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-06-11 22:08:40,993:INFO:Calculating mean and std
2025-06-11 22:08:40,994:INFO:Creating metrics dataframe
2025-06-11 22:08:40,997:INFO:Uploading results into container
2025-06-11 22:08:40,998:INFO:Uploading model into container now
2025-06-11 22:08:40,998:INFO:_master_model_container: 6
2025-06-11 22:08:40,998:INFO:_display_container: 2
2025-06-11 22:08:40,999:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=606, solver='auto',
                tol=0.0001)
2025-06-11 22:08:40,999:INFO:create_model() successfully completed......................................
2025-06-11 22:08:41,115:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:41,115:INFO:Creating metrics dataframe
2025-06-11 22:08:41,120:INFO:Initializing Random Forest Classifier
2025-06-11 22:08:41,120:INFO:Total runtime is 0.28263185421625775 minutes
2025-06-11 22:08:41,121:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:41,121:INFO:Initializing create_model()
2025-06-11 22:08:41,121:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:41,121:INFO:Checking exceptions
2025-06-11 22:08:41,121:INFO:Importing libraries
2025-06-11 22:08:41,121:INFO:Copying training dataset
2025-06-11 22:08:41,124:INFO:Defining folds
2025-06-11 22:08:41,124:INFO:Declaring metric variables
2025-06-11 22:08:41,125:INFO:Importing untrained model
2025-06-11 22:08:41,125:INFO:Random Forest Classifier Imported successfully
2025-06-11 22:08:41,125:INFO:Starting cross validation
2025-06-11 22:08:41,127:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:42,410:INFO:Calculating mean and std
2025-06-11 22:08:42,411:INFO:Creating metrics dataframe
2025-06-11 22:08:42,415:INFO:Uploading results into container
2025-06-11 22:08:42,416:INFO:Uploading model into container now
2025-06-11 22:08:42,416:INFO:_master_model_container: 7
2025-06-11 22:08:42,416:INFO:_display_container: 2
2025-06-11 22:08:42,417:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=606, verbose=0, warm_start=False)
2025-06-11 22:08:42,417:INFO:create_model() successfully completed......................................
2025-06-11 22:08:42,529:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:42,529:INFO:Creating metrics dataframe
2025-06-11 22:08:42,534:INFO:Initializing Quadratic Discriminant Analysis
2025-06-11 22:08:42,534:INFO:Total runtime is 0.306201982498169 minutes
2025-06-11 22:08:42,534:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:42,534:INFO:Initializing create_model()
2025-06-11 22:08:42,534:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:42,534:INFO:Checking exceptions
2025-06-11 22:08:42,535:INFO:Importing libraries
2025-06-11 22:08:42,535:INFO:Copying training dataset
2025-06-11 22:08:42,538:INFO:Defining folds
2025-06-11 22:08:42,538:INFO:Declaring metric variables
2025-06-11 22:08:42,539:INFO:Importing untrained model
2025-06-11 22:08:42,539:INFO:Quadratic Discriminant Analysis Imported successfully
2025-06-11 22:08:42,539:INFO:Starting cross validation
2025-06-11 22:08:42,540:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:42,604:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,614:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,614:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,617:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,619:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,624:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,634:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,637:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,707:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,711:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-06-11 22:08:42,758:INFO:Calculating mean and std
2025-06-11 22:08:42,759:INFO:Creating metrics dataframe
2025-06-11 22:08:42,762:INFO:Uploading results into container
2025-06-11 22:08:42,762:INFO:Uploading model into container now
2025-06-11 22:08:42,763:INFO:_master_model_container: 8
2025-06-11 22:08:42,763:INFO:_display_container: 2
2025-06-11 22:08:42,763:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2025-06-11 22:08:42,763:INFO:create_model() successfully completed......................................
2025-06-11 22:08:42,861:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:42,861:INFO:Creating metrics dataframe
2025-06-11 22:08:42,864:INFO:Initializing Ada Boost Classifier
2025-06-11 22:08:42,864:INFO:Total runtime is 0.31169768174489343 minutes
2025-06-11 22:08:42,865:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:42,865:INFO:Initializing create_model()
2025-06-11 22:08:42,865:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:42,865:INFO:Checking exceptions
2025-06-11 22:08:42,865:INFO:Importing libraries
2025-06-11 22:08:42,865:INFO:Copying training dataset
2025-06-11 22:08:42,869:INFO:Defining folds
2025-06-11 22:08:42,869:INFO:Declaring metric variables
2025-06-11 22:08:42,869:INFO:Importing untrained model
2025-06-11 22:08:42,869:INFO:Ada Boost Classifier Imported successfully
2025-06-11 22:08:42,869:INFO:Starting cross validation
2025-06-11 22:08:42,870:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:43,444:INFO:Calculating mean and std
2025-06-11 22:08:43,444:INFO:Creating metrics dataframe
2025-06-11 22:08:43,448:INFO:Uploading results into container
2025-06-11 22:08:43,448:INFO:Uploading model into container now
2025-06-11 22:08:43,449:INFO:_master_model_container: 9
2025-06-11 22:08:43,449:INFO:_display_container: 2
2025-06-11 22:08:43,449:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606)
2025-06-11 22:08:43,449:INFO:create_model() successfully completed......................................
2025-06-11 22:08:43,549:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:43,549:INFO:Creating metrics dataframe
2025-06-11 22:08:43,554:INFO:Initializing Gradient Boosting Classifier
2025-06-11 22:08:43,554:INFO:Total runtime is 0.3232054074605306 minutes
2025-06-11 22:08:43,554:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:43,554:INFO:Initializing create_model()
2025-06-11 22:08:43,555:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:43,555:INFO:Checking exceptions
2025-06-11 22:08:43,555:INFO:Importing libraries
2025-06-11 22:08:43,555:INFO:Copying training dataset
2025-06-11 22:08:43,558:INFO:Defining folds
2025-06-11 22:08:43,558:INFO:Declaring metric variables
2025-06-11 22:08:43,558:INFO:Importing untrained model
2025-06-11 22:08:43,559:INFO:Gradient Boosting Classifier Imported successfully
2025-06-11 22:08:43,559:INFO:Starting cross validation
2025-06-11 22:08:43,560:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:44,448:INFO:Calculating mean and std
2025-06-11 22:08:44,449:INFO:Creating metrics dataframe
2025-06-11 22:08:44,451:INFO:Uploading results into container
2025-06-11 22:08:44,452:INFO:Uploading model into container now
2025-06-11 22:08:44,452:INFO:_master_model_container: 10
2025-06-11 22:08:44,452:INFO:_display_container: 2
2025-06-11 22:08:44,453:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=606, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2025-06-11 22:08:44,453:INFO:create_model() successfully completed......................................
2025-06-11 22:08:44,552:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:44,553:INFO:Creating metrics dataframe
2025-06-11 22:08:44,556:INFO:Initializing Linear Discriminant Analysis
2025-06-11 22:08:44,556:INFO:Total runtime is 0.3399031043052673 minutes
2025-06-11 22:08:44,556:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:44,557:INFO:Initializing create_model()
2025-06-11 22:08:44,557:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:44,557:INFO:Checking exceptions
2025-06-11 22:08:44,557:INFO:Importing libraries
2025-06-11 22:08:44,557:INFO:Copying training dataset
2025-06-11 22:08:44,560:INFO:Defining folds
2025-06-11 22:08:44,560:INFO:Declaring metric variables
2025-06-11 22:08:44,561:INFO:Importing untrained model
2025-06-11 22:08:44,561:INFO:Linear Discriminant Analysis Imported successfully
2025-06-11 22:08:44,561:INFO:Starting cross validation
2025-06-11 22:08:44,562:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:44,753:INFO:Calculating mean and std
2025-06-11 22:08:44,754:INFO:Creating metrics dataframe
2025-06-11 22:08:44,758:INFO:Uploading results into container
2025-06-11 22:08:44,758:INFO:Uploading model into container now
2025-06-11 22:08:44,758:INFO:_master_model_container: 11
2025-06-11 22:08:44,758:INFO:_display_container: 2
2025-06-11 22:08:44,758:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2025-06-11 22:08:44,758:INFO:create_model() successfully completed......................................
2025-06-11 22:08:44,855:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:44,855:INFO:Creating metrics dataframe
2025-06-11 22:08:44,859:INFO:Initializing Extra Trees Classifier
2025-06-11 22:08:44,859:INFO:Total runtime is 0.3449578404426575 minutes
2025-06-11 22:08:44,859:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:44,859:INFO:Initializing create_model()
2025-06-11 22:08:44,859:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:44,859:INFO:Checking exceptions
2025-06-11 22:08:44,859:INFO:Importing libraries
2025-06-11 22:08:44,859:INFO:Copying training dataset
2025-06-11 22:08:44,863:INFO:Defining folds
2025-06-11 22:08:44,863:INFO:Declaring metric variables
2025-06-11 22:08:44,863:INFO:Importing untrained model
2025-06-11 22:08:44,863:INFO:Extra Trees Classifier Imported successfully
2025-06-11 22:08:44,863:INFO:Starting cross validation
2025-06-11 22:08:44,864:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:45,858:INFO:Calculating mean and std
2025-06-11 22:08:45,859:INFO:Creating metrics dataframe
2025-06-11 22:08:45,862:INFO:Uploading results into container
2025-06-11 22:08:45,863:INFO:Uploading model into container now
2025-06-11 22:08:45,863:INFO:_master_model_container: 12
2025-06-11 22:08:45,863:INFO:_display_container: 2
2025-06-11 22:08:45,864:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=606, verbose=0, warm_start=False)
2025-06-11 22:08:45,864:INFO:create_model() successfully completed......................................
2025-06-11 22:08:45,964:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:45,964:INFO:Creating metrics dataframe
2025-06-11 22:08:45,969:INFO:Initializing Light Gradient Boosting Machine
2025-06-11 22:08:45,969:INFO:Total runtime is 0.3634421745936076 minutes
2025-06-11 22:08:45,969:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:45,970:INFO:Initializing create_model()
2025-06-11 22:08:45,970:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:45,970:INFO:Checking exceptions
2025-06-11 22:08:45,970:INFO:Importing libraries
2025-06-11 22:08:45,970:INFO:Copying training dataset
2025-06-11 22:08:45,973:INFO:Defining folds
2025-06-11 22:08:45,973:INFO:Declaring metric variables
2025-06-11 22:08:45,973:INFO:Importing untrained model
2025-06-11 22:08:45,973:INFO:Light Gradient Boosting Machine Imported successfully
2025-06-11 22:08:45,974:INFO:Starting cross validation
2025-06-11 22:08:45,974:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:08:47,755:INFO:Calculating mean and std
2025-06-11 22:08:47,756:INFO:Creating metrics dataframe
2025-06-11 22:08:47,763:INFO:Uploading results into container
2025-06-11 22:08:47,764:INFO:Uploading model into container now
2025-06-11 22:08:47,764:INFO:_master_model_container: 13
2025-06-11 22:08:47,764:INFO:_display_container: 2
2025-06-11 22:08:47,765:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=606, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2025-06-11 22:08:47,765:INFO:create_model() successfully completed......................................
2025-06-11 22:08:47,894:INFO:SubProcess create_model() end ==================================
2025-06-11 22:08:47,894:INFO:Creating metrics dataframe
2025-06-11 22:08:47,899:INFO:Initializing CatBoost Classifier
2025-06-11 22:08:47,899:INFO:Total runtime is 0.3956250627835592 minutes
2025-06-11 22:08:47,899:INFO:SubProcess create_model() called ==================================
2025-06-11 22:08:47,899:INFO:Initializing create_model()
2025-06-11 22:08:47,899:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:08:47,899:INFO:Checking exceptions
2025-06-11 22:08:47,900:INFO:Importing libraries
2025-06-11 22:08:47,900:INFO:Copying training dataset
2025-06-11 22:08:47,904:INFO:Defining folds
2025-06-11 22:08:47,904:INFO:Declaring metric variables
2025-06-11 22:08:47,904:INFO:Importing untrained model
2025-06-11 22:08:47,904:INFO:CatBoost Classifier Imported successfully
2025-06-11 22:08:47,904:INFO:Starting cross validation
2025-06-11 22:08:47,906:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:09:02,547:INFO:Calculating mean and std
2025-06-11 22:09:02,547:INFO:Creating metrics dataframe
2025-06-11 22:09:02,553:INFO:Uploading results into container
2025-06-11 22:09:02,554:INFO:Uploading model into container now
2025-06-11 22:09:02,554:INFO:_master_model_container: 14
2025-06-11 22:09:02,554:INFO:_display_container: 2
2025-06-11 22:09:02,554:INFO:<catboost.core.CatBoostClassifier object at 0x0000016970DA8950>
2025-06-11 22:09:02,554:INFO:create_model() successfully completed......................................
2025-06-11 22:09:02,693:INFO:SubProcess create_model() end ==================================
2025-06-11 22:09:02,693:INFO:Creating metrics dataframe
2025-06-11 22:09:02,700:INFO:Initializing Dummy Classifier
2025-06-11 22:09:02,700:INFO:Total runtime is 0.642298177878062 minutes
2025-06-11 22:09:02,700:INFO:SubProcess create_model() called ==================================
2025-06-11 22:09:02,700:INFO:Initializing create_model()
2025-06-11 22:09:02,701:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x00000169722B7E50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:09:02,701:INFO:Checking exceptions
2025-06-11 22:09:02,701:INFO:Importing libraries
2025-06-11 22:09:02,701:INFO:Copying training dataset
2025-06-11 22:09:02,705:INFO:Defining folds
2025-06-11 22:09:02,705:INFO:Declaring metric variables
2025-06-11 22:09:02,705:INFO:Importing untrained model
2025-06-11 22:09:02,705:INFO:Dummy Classifier Imported successfully
2025-06-11 22:09:02,707:INFO:Starting cross validation
2025-06-11 22:09:02,708:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-06-11 22:09:02,865:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:02,917:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:02,937:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:02,946:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:02,949:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:02,983:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:02,996:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:03,010:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:03,019:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:03,058:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-06-11 22:09:03,066:INFO:Calculating mean and std
2025-06-11 22:09:03,066:INFO:Creating metrics dataframe
2025-06-11 22:09:03,073:INFO:Uploading results into container
2025-06-11 22:09:03,074:INFO:Uploading model into container now
2025-06-11 22:09:03,074:INFO:_master_model_container: 15
2025-06-11 22:09:03,075:INFO:_display_container: 2
2025-06-11 22:09:03,075:INFO:DummyClassifier(constant=None, random_state=606, strategy='prior')
2025-06-11 22:09:03,075:INFO:create_model() successfully completed......................................
2025-06-11 22:09:03,197:INFO:SubProcess create_model() end ==================================
2025-06-11 22:09:03,197:INFO:Creating metrics dataframe
2025-06-11 22:09:03,204:INFO:Initializing create_model()
2025-06-11 22:09:03,204:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-06-11 22:09:03,204:INFO:Checking exceptions
2025-06-11 22:09:03,205:INFO:Importing libraries
2025-06-11 22:09:03,205:INFO:Copying training dataset
2025-06-11 22:09:03,208:INFO:Defining folds
2025-06-11 22:09:03,208:INFO:Declaring metric variables
2025-06-11 22:09:03,208:INFO:Importing untrained model
2025-06-11 22:09:03,208:INFO:Declaring custom model
2025-06-11 22:09:03,209:INFO:Ada Boost Classifier Imported successfully
2025-06-11 22:09:03,210:INFO:Cross validation set to False
2025-06-11 22:09:03,210:INFO:Fitting Model
2025-06-11 22:09:03,336:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606)
2025-06-11 22:09:03,336:INFO:create_model() successfully completed......................................
2025-06-11 22:09:03,431:INFO:Creating Dashboard logs
2025-06-11 22:09:03,431:INFO:Model: Ada Boost Classifier
2025-06-11 22:09:03,550:INFO:Logged params: {'algorithm': 'SAMME.R', 'base_estimator': 'deprecated', 'estimator': None, 'learning_rate': 1.0, 'n_estimators': 50, 'random_state': 606}
2025-06-11 22:09:03,867:INFO:Initializing predict_model()
2025-06-11 22:09:03,867:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=False, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001697250D260>)
2025-06-11 22:09:03,867:INFO:Checking exceptions
2025-06-11 22:09:03,867:INFO:Preloading libraries
2025-06-11 22:09:04,061:WARNING:C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

2025-06-11 22:09:04,241:INFO:Creating Dashboard logs
2025-06-11 22:09:04,241:INFO:Model: CatBoost Classifier
2025-06-11 22:09:04,319:WARNING:Couldn't get params for model. Exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycaret\loggers\dashboard_logger.py", line 78, in log_model
    params = params.get_all_params()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\catboost\core.py", line 3504, in get_all_params
    raise CatBoostError("There is no trained model to use get_all_params(). Use fit() to train model. Then use this method.")
_catboost.CatBoostError: There is no trained model to use get_all_params(). Use fit() to train model. Then use this method.

2025-06-11 22:09:04,319:INFO:Logged params: {}
2025-06-11 22:09:04,745:INFO:Creating Dashboard logs
2025-06-11 22:09:04,745:INFO:Model: Gradient Boosting Classifier
2025-06-11 22:09:04,823:INFO:Logged params: {'ccp_alpha': 0.0, 'criterion': 'friedman_mse', 'init': None, 'learning_rate': 0.1, 'loss': 'log_loss', 'max_depth': 3, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_iter_no_change': None, 'random_state': 606, 'subsample': 1.0, 'tol': 0.0001, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False}
2025-06-11 22:09:05,272:INFO:Creating Dashboard logs
2025-06-11 22:09:05,272:INFO:Model: Decision Tree Classifier
2025-06-11 22:09:05,349:INFO:Logged params: {'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'random_state': 606, 'splitter': 'best'}
2025-06-11 22:09:05,791:INFO:Creating Dashboard logs
2025-06-11 22:09:05,791:INFO:Model: Random Forest Classifier
2025-06-11 22:09:05,873:INFO:Logged params: {'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 606, 'verbose': 0, 'warm_start': False}
2025-06-11 22:09:06,321:INFO:Creating Dashboard logs
2025-06-11 22:09:06,322:INFO:Model: Light Gradient Boosting Machine
2025-06-11 22:09:06,417:INFO:Logged params: {'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 1.0, 'importance_type': 'split', 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'num_leaves': 31, 'objective': None, 'random_state': 606, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0}
2025-06-11 22:09:06,930:INFO:Creating Dashboard logs
2025-06-11 22:09:06,931:INFO:Model: Extra Trees Classifier
2025-06-11 22:09:07,030:INFO:Logged params: {'bootstrap': False, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 606, 'verbose': 0, 'warm_start': False}
2025-06-11 22:09:07,573:INFO:Creating Dashboard logs
2025-06-11 22:09:07,573:INFO:Model: Logistic Regression
2025-06-11 22:09:07,692:INFO:Logged params: {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 606, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}
2025-06-11 22:09:08,222:INFO:Creating Dashboard logs
2025-06-11 22:09:08,222:INFO:Model: Ridge Classifier
2025-06-11 22:09:08,302:INFO:Logged params: {'alpha': 1.0, 'class_weight': None, 'copy_X': True, 'fit_intercept': True, 'max_iter': None, 'positive': False, 'random_state': 606, 'solver': 'auto', 'tol': 0.0001}
2025-06-11 22:09:08,738:INFO:Creating Dashboard logs
2025-06-11 22:09:08,738:INFO:Model: Linear Discriminant Analysis
2025-06-11 22:09:08,824:INFO:Logged params: {'covariance_estimator': None, 'n_components': None, 'priors': None, 'shrinkage': None, 'solver': 'svd', 'store_covariance': False, 'tol': 0.0001}
2025-06-11 22:09:09,273:INFO:Creating Dashboard logs
2025-06-11 22:09:09,273:INFO:Model: Naive Bayes
2025-06-11 22:09:09,355:INFO:Logged params: {'priors': None, 'var_smoothing': 1e-09}
2025-06-11 22:09:09,797:INFO:Creating Dashboard logs
2025-06-11 22:09:09,797:INFO:Model: K Neighbors Classifier
2025-06-11 22:09:09,879:INFO:Logged params: {'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': -1, 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}
2025-06-11 22:09:10,339:INFO:Creating Dashboard logs
2025-06-11 22:09:10,339:INFO:Model: Quadratic Discriminant Analysis
2025-06-11 22:09:10,455:INFO:Logged params: {'priors': None, 'reg_param': 0.0, 'store_covariance': False, 'tol': 0.0001}
2025-06-11 22:09:10,994:INFO:Creating Dashboard logs
2025-06-11 22:09:10,994:INFO:Model: Dummy Classifier
2025-06-11 22:09:11,098:INFO:Logged params: {'constant': None, 'random_state': 606, 'strategy': 'prior'}
2025-06-11 22:09:11,657:INFO:Creating Dashboard logs
2025-06-11 22:09:11,657:INFO:Model: SVM - Linear Kernel
2025-06-11 22:09:11,747:INFO:Logged params: {'alpha': 0.0001, 'average': False, 'class_weight': None, 'early_stopping': False, 'epsilon': 0.1, 'eta0': 0.001, 'fit_intercept': True, 'l1_ratio': 0.15, 'learning_rate': 'optimal', 'loss': 'hinge', 'max_iter': 1000, 'n_iter_no_change': 5, 'n_jobs': -1, 'penalty': 'l2', 'power_t': 0.5, 'random_state': 606, 'shuffle': True, 'tol': 0.001, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False}
2025-06-11 22:09:12,271:INFO:_master_model_container: 15
2025-06-11 22:09:12,271:INFO:_display_container: 2
2025-06-11 22:09:12,271:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606)
2025-06-11 22:09:12,271:INFO:compare_models() successfully completed......................................
2025-06-11 22:09:12,272:INFO:Initializing evaluate_model()
2025-06-11 22:09:12,272:INFO:evaluate_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606), fold=None, fit_kwargs=None, plot_kwargs=None, feature_name=None, groups=None)
2025-06-11 22:09:12,333:INFO:Initializing plot_model()
2025-06-11 22:09:12,333:INFO:plot_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001696D40F150>, estimator=AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606), plot=pipeline, scale=1, save=False, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), fit_kwargs={}, plot_kwargs=None, groups=None, feature_name=None, label=False, verbose=False, system=True, display=None, display_format=None)
2025-06-11 22:09:12,333:INFO:Checking exceptions
2025-06-11 22:09:12,335:INFO:Preloading libraries
2025-06-11 22:09:12,338:INFO:Copying training dataset
2025-06-11 22:09:12,339:INFO:Plot type: pipeline
2025-06-11 22:09:20,874:INFO:Visual Rendered Successfully
2025-06-11 22:09:20,984:INFO:plot_model() successfully completed......................................
2025-06-11 22:09:20,989:INFO:Initializing save_model()
2025-06-11 22:09:20,989:INFO:save_model(model=AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=606), model_name=credit_model, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\User\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'monthly_income_usd',
                                             'app_usage_score',
                                             'digital_profile_strength',
                                             'num_contacts_uploaded',
                                             'political_event_last_month'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_e...
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('onehot_encoding',
                 TransformerWrapper(exclude=None,
                                    include=['residence_risk_zone'],
                                    transformer=OneHotEncoder(cols=['residence_risk_zone'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0)))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2025-06-11 22:09:20,989:INFO:Adding model into prep_pipe
2025-06-11 22:09:21,005:INFO:credit_model.pkl saved in current working directory
2025-06-11 22:09:21,009:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'monthly_income_usd',
                                             'app_usage_score',
                                             'digital_profile_strength',
                                             'num_contacts_uploaded',
                                             'political_event_last_month'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,...
                                    include=['residence_risk_zone'],
                                    transformer=OneHotEncoder(cols=['residence_risk_zone'],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('trained_model',
                 AdaBoostClassifier(algorithm='SAMME.R',
                                    base_estimator='deprecated', estimator=None,
                                    learning_rate=1.0, n_estimators=50,
                                    random_state=606))],
         verbose=False)
2025-06-11 22:09:21,010:INFO:save_model() successfully completed......................................
2025-06-11 22:09:41,808:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:09:41,808:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:09:41,809:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:09:41,809:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-06-11 22:09:43,959:INFO:Initializing load_model()
2025-06-11 22:09:43,960:INFO:load_model(model_name=credit_model, platform=None, authentication=None, verbose=True)
